# Generated by Django 2.1.3 on 2019-01-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['priority', 'deadline']},
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('1', '중요'), ('2', '보통'), ('3', '사소')], default='2', max_length=1),
        ),
    ]
